pipeline:
  build:
    image: hseeberger/scala-sbt:8u171_2.12.6_1.1.6
    commands:
      - sbt test

  slack:
    image: plugins/slack
    secrets: [ plugin_webhook ]
    channel: 'daf-devel'
    template: >
      {{#success build.status}}
        Build {{build.number}} for repo {{repo.name}} by {{build.author}} succeeded!
      {{else}}
        Build {{build.number}} for repo {{repo.name}} by {{build.author}} failed! 
      {{/success}}


