language: scala

jdk: oraclejdk8

scala:
  - 2.11.12
  - 2.12.4
script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts test

notifications:
  email:
    recipients:
      - fabio@teamdigitale.governo.it
      - fabiana@teamdigitale.governo.it
